---
name: Leo Puentes
description: Blog de conocimiento Motivación - Programación - Inversión
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: leopolseo@gmail.com
mailchimp-list: https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  sal:
    name: Leo Puentes
    site: https://leopuentes.me
    avatar: "/assets/images/avatar1.jpg"
    bio: 'Impulsar el potencial de Internet es mi pasión. He decidido crear este blog
      donde deseo y quiero compartir todo el conocimiento que he aprendido y el que
      voy aprendiendo. Me gusta enseñar y junto a ello he desarrollado habilidades
      para Motivar, Programar e Invertir. Todo lo que soy esta en este blog, espero
      sea de tu agrado y podamos aprende '
    email: jholepual@gmail.com
    twitter: ''
  jane:
    name: Jane
    site: https://www.wowthemes.net
    avatar: "/assets/images/avatar2.jpg"
    bio: Blogger, fashionista, love to explore new ideas and write on my morning coffee!
    email: fakemail@gmail.com
    twitter: https://twitter.com/wowthemesnet
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: sal
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
