name: Leo Puentes
url: https://www.leopuentes.me
description: Desarrolla habilidades y conocimientos no solo en Programación. Crece como Persona y Edúcate Financieramente para una vida equilibrada.
logo: /assets/images/logo/Logo-leo-web-seo.webp
logo-donar: /assets/images/logo/buy-coffee.webp
logo-pie: /assets/images/logo/logo-leo-puentes.webp
email: leopolseo@gmail.com
author: Leonardo Puentes
headers:
  Content-Security-Policy: upgrade-insecure-requests
  Strict-Transport-Security: max-age=631138519; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-Download-Options: noopen
  X-Frame-Options: DENY
  X-Permitted-Cross-Domain-Policies: none
  X-Xss-Protection: 1; mode=block
  Referrer-Policy: no-referrer
  Feature-Policy: accelerometer 'none'; autoplay 'self'; camera 'none'; encrypted-media 'self'; fullscreen 'self'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'self'; picture-in-picture 'self'; sync-xhr 'self'; usb 'none'
  Expect-CT: enforce,max-age=2592000,report-uri="https://www.leopuentes.me"
include:
- _pages