name: Leo Puentes
description: Desarrolla habilidades y conocimientos no solo en Programación. Crece como Persona y Edúcate Financieramente para una vida equilibrada.
logo: /assets/images/logo/Logo leo web seo.webp
logo-donar: /assets/images/logo/buy-coffee.svg
logo-pie: /assets/images/logo/logo-leo-puentes.webp
email: leopolseo@gmail.com
author: Leonardo Puentes
include:
- _pages